version: '3.7'

services:
  server:
    build: server
    volumes:
      - ./code/exercises:/exercises
      - ./run.sh:/exercises/${EXERCISE}/run.sh
    ports:
      - 9000:9000
      - 9001:9001
      - 9002:9002
    working_dir: /exercises/${EXERCISE}
    command: ./run.sh
